<a href="https://colab.research.google.com/github/Lyanan85/In-GameSeries/blob/venv/notebook_pivot_table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Criando tabulações com pivot_table**

###**Carregando os dados**

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/alura-cursos/python_dados/refs/heads/main/Dados/contagem_bicicletas.csv')

Neste conjunto de dados, temos informações sobre uma empresa que realiza o aluguel de bicicletas. O DataFrame contém registros detalhados, como o número de bicicletas alugadas por dia e horário, condições climáticas e informações sobre finais feriados e finais de semana:

In [ ]:
df.head()

,data_hora,contagem,temperatura,sensacao_termica,umidade,velocidade_vento,clima,feriado,fim_de_semana,estacao
0,2015-01-04 00:00:00,182,3.00,2.00,93.0,6.0,Nublado,Não,Sim,Inverno
1,2015-01-04 01:00:00,138,2.75,2.25,93.0,5.0,Céu limpo,Não,Sim,Inverno
2,2015-01-04 02:00:00,134,2.50,2.50,96.5,0.0,Céu limpo,Não,Sim,Inverno
3,2015-01-04 03:00:00,72,2.00,2.00,100.0,0.0,Céu limpo,Não,Sim,Inverno
4,2015-01-04 04:00:00,47,2.00,2.00,93.0,6.5,Céu limpo,Não,Sim,Inverno

###**Utilizando o método pivot_table**

O método [pivot_table()](https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html) permite agrupar e reorganizar os dados de maneira semelhante a uma tabela dinâmica. Embora chegue aos mesmos resultados do `groupby()` ele oferece vantagens adicionais que podem facilitar a análise, as quais vamos explorar ao longo deste curso.

Vamos começar criando uma tabela que mostre a média de bicicletas alugadas por tipo de clima. Para isso, precisamos especificar o dataframe que estamos utilizando, a coluna que contém os valores a serem analisados (neste caso, a coluna `contagem`), e a coluna que será usada como índice, que será a coluna `clima`. O `pivot_table()` calcula automaticamente a média, pois essa é a função de agregação padrão. Portanto, o único passo necessário é indicar essas informações, e o `pivot_table()` cuidará do restante:

In [ ]:
pivot_clima = pd.pivot_table(df, values='contagem', index='clima')
pivot_clima

                         contagem
clima
Chuva com trovoadas    583.428571
Chuva leve             712.966371
Céu limpo             1162.088943
Neve                   250.850000
Nublado               1195.124472
Parcialmente nublado  1266.925791

Além da média, que é calculada por padrão, é possível personalizar as operações realizadas através do uso de diferentes métodos como a soma `sum()` para obter insights específicos:

In [ ]:
pivot_clima = pd.pivot_table(df, values='contagem', index='clima', aggfunc='sum')
pivot_clima

                      contagem
clima
Chuva com trovoadas       8168
Chuva leve             1526461
Céu limpo              7146847
Neve                     15051
Nublado                4243887
Parcialmente nublado   6965558

>👩‍💻***Dica da Val:*** Podemos ordenar os dados para tornar a análise mais clara e intuitiva, com uso do método `sort_values(ascending=False)`.

Também podemos criar uma tabela multi-index, adicionando mais de uma coluna ao `index`:

In [3]:
pivot_clima_estacao = pd.pivot_table(df, values='contagem', index=['estacao', 'clima'], aggfunc='mean')
pivot_clima_estacao

                                   contagem
estacao   clima
Inverno   Chuva com trovoadas    228.000000
          Chuva leve             542.968153
          Céu limpo              760.163115
          Neve                   318.409091
          Nublado                971.990635
          Parcialmente nublado   908.796070
Outono    Chuva com trovoadas    242.000000
          Chuva leve             788.809249
          Céu limpo             1130.973451
          Neve                    59.300000
          Nublado               1281.383778
          Parcialmente nublado  1304.220484
Primavera Chuva com trovoadas    798.428571
          Chuva leve             677.873162
          Céu limpo             1144.472603
          Neve                    74.666667
          Nublado               1162.028607
          Parcialmente nublado  1199.101483
Verão     Chuva com trovoadas    421.800000
          Chuva leve             905.160000
          Céu limpo             1471.312843
          Nublado               1393.618065
          Parcialmente nublado  1688.683146

Se quisermos reorganizar a estrutura da tabela, o processo é bem simples. Podemos definir as colunas utilizando o parâmetro `columns`:

In [5]:
pivot_clima_estacao = pd.pivot_table(df, values='contagem', index=['estacao'], columns=['clima'], aggfunc='mean')
pivot_clima_estacao

clima,Chuva com trovoadas,Chuva leve,Céu limpo,Neve,Nublado,Parcialmente nublado
estacao,,,,,,
Inverno,228.000000,542.968153,760.163115,318.409091,971.990635,908.796070
Outono,242.000000,788.809249,1130.973451,59.300000,1281.383778,1304.220484
Primavera,798.428571,677.873162,1144.472603,74.666667,1162.028607,1199.101483
Verão,421.800000,905.160000,1471.312843,NaN,1393.618065,1688.683146

Para realizar múltiplas agregações, podemos usar o parâmetro `aggfunc` e especificar uma função de agregação diferente para cada coluna, através de um dicionário. No exemplo abaixo, estamos aplicando a soma para a coluna `contagem` e a média para as colunas `temperatura`, `sensação térmica` e `umidade`:

In [7]:
pivot_agregacoes = df.pivot_table(
    index=['estacao', 'clima'],
    values=['contagem', 'temperatura', 'sensacao_termica', 'umidade'],
    aggfunc={
        'contagem': 'sum',
        'temperatura': 'mean',
        'sensacao_termica': 'mean',
        'umidade': 'mean'
    }
)
pivot_agregacoes

                                contagem  sensacao_termica  temperatura  \
estacao   clima
Inverno   Chuva com trovoadas        228          6.500000    10.000000
          Chuva leve              340984          7.188296     9.046576
          Céu limpo               927399          3.811066     6.022336
          Neve                     14010          1.568182     4.375000
          Nublado                 934083          7.008585     8.754422
          Parcialmente nublado   1341383          5.933096     7.887873
Outono    Chuva com trovoadas        242         18.500000    18.500000
          Chuva leve              409392         12.222543    12.830443
          Céu limpo              1533600         11.516962    12.233776
          Neve                       593          3.800000     7.400000
          Nublado                1295479         13.331355    13.689416
          Parcialmente nublado   1833734         13.035799    13.461830
Primavera Chuva com trovoadas       5589          7.785714     9.785714
          Chuva leve              368763          8.657169    10.186581
          Céu limpo              2005116          9.775970    10.843322
          Neve                       448          5.083333     7.833333
          Nublado                 934271          9.302861    10.582090
          Parcialmente nublado   1536049          9.370414    10.700234
Verão     Chuva com trovoadas       2109         18.200000    18.200000
          Chuva leve              407322         17.064444    17.065556
          Céu limpo              2680732         18.855653    18.930845
          Nublado                1080054         17.545806    17.558710
          Parcialmente nublado   2254392         18.685393    18.716854

                                  umidade
estacao   clima
Inverno   Chuva com trovoadas   88.000000
          Chuva leve            83.739650
          Céu limpo             76.006148
          Neve                  87.829545
          Nublado               78.369927
          Parcialmente nublado  76.405149
Outono    Chuva com trovoadas   91.000000
          Chuva leve            84.075145
          Céu limpo             74.282448
          Neve                  91.550000
          Nublado               78.105341
          Parcialmente nublado  73.333926
Primavera Chuva com trovoadas   63.071429
          Chuva leve            80.169118
          Céu limpo             64.142694
          Neve                  91.250000
          Nublado               73.543532
          Parcialmente nublado  66.598556
Verão     Chuva com trovoadas   85.500000
          Chuva leve            81.085556
          Céu limpo             61.675906
          Nublado               73.968387
          Parcialmente nublado  64.894757

>
👩‍💻***Dica da Val:*** Após a agregação, podemos renomear as colunas para torná-las mais descritivas e intuitivas.

Com o `pivot_table()`, também podemos ativar a opção `margins=True`, que adiciona automaticamente uma linha e uma coluna ao final da tabela, exibindo os valores gerais para cada métrica. Dependendo da função de agregação utilizada, o comportamento será o seguinte: se for aplicada a média, ele calculará a média de todas as linhas e colunas; se for utilizada a soma, ele somará os valores; se for o valor mínimo, ele mostrará o menor valor de cada linha e coluna, e assim por diante. Esse recurso facilita a visualização dos totais e resumos das métricas na tabela.

No exemplo abaixo, como estamos utilizando a função de soma, ele somou os valores de todas as linhas e colunas.

Essa funcionalidade é útil para obter uma visão rápida do comportamento geral dos dados, sem precisar de cálculos adicionais.

Além disso, o `pivot_table()` oferece o parâmetro `fill_value`, que preenche os valores nulos (NaN) com um valor especificado, como 0, por exemplo, o que ajuda a evitar lacunas nos resultados:

In [28]:
pivot_table = df.pivot_table(
    index='estacao',
    columns='clima',
    values='contagem',
    aggfunc={'contagem': 'sum'},
    margins=True,
    margins_name='Total',
    fill_value=0
)
pivot_table

KeyError: 'contagem'

Com isso, podemos concluir que o `pivot_table()` é bastante flexível, permitindo agrupar dados, aplicar funções de agregação e ainda adicionar totais gerais com o parâmetro margins. Além de lidar com valores nulos de forma simples.

In [13]:
df=pd.read_csv("https://raw.githubusercontent.com/alura-cursos/python_dados/refs/heads/main/Dados/loja_vendas.csv")
df

,ID_compra,unidade,cidade,data,horario,categoria_produto,valor_unitario,quantidade,valor_total,metodo_pagamento,ID_cliente,programa_cashback,idade,avaliacao_compra
0,6,Parque das nações,Santo André,2022-01-03,15:40,Eletrônicos,4457.9,4,17831.6,Dinheiro,6149,Sim,30,10
1,5,Oswaldo Cruz,São Caetano do Sul,2022-01-03,16:48,Ferramentas e construção,115.9,1,115.9,PIX,9491,Sim,36,9
2,9,Paulicéia,São Bernardo do Campo,2022-01-03,12:08,Beleza e cuidados pessoais,68.9,2,137.8,Cartão,5288,Não,39,9
3,4,Oswaldo Cruz,São Caetano do Sul,2022-01-03,9:29,Ferramentas e construção,80.9,5,404.5,PIX,9679,Sim,35,10
4,8,Parque das nações,Santo André,2022-01-03,13:02,Beleza e cuidados pessoais,165.0,4,660.0,PIX,1380,Não,50,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6164,6141,Oswaldo Cruz,São Caetano do Sul,2022-12-31,12:49,Eletrônicos,1509.9,5,7549.5,Cartão,6035,Não,49,10
6165,6148,Paulicéia,São Bernardo do Campo,2022-12-31,18:02,Papelaria e escritório,14.0,2,28.0,PIX,7361,Sim,40,9
6166,6123,Paulicéia,São Bernardo do Campo,2022-12-31,16:25,Alimentos e bebidas,77.9,1,77.9,Cartão,4516,Não,32,8
6167,6147,Oswaldo Cruz,São Caetano do Sul,2022-12-31,16:38,Livros,142.9,4,571.6,Cartão,3786,Não,34,10
6168,6122,Oswaldo Cruz,São Caetano do Sul,2022-12-31,17:11,Beleza e cuidados pessoais,89.9,5,449.5,Cartão,8022,Sim,20,9

In [19]:
df.head()

,ID_compra,unidade,cidade,data,horario,categoria_produto,valor_unitario,quantidade,valor_total,metodo_pagamento,ID_cliente,programa_cashback,idade,avaliacao_compra
0,6,Parque das nações,Santo André,2022-01-03,15:40,Eletrônicos,4457.9,4,17831.6,Dinheiro,6149,Sim,30,10
1,5,Oswaldo Cruz,São Caetano do Sul,2022-01-03,16:48,Ferramentas e construção,115.9,1,115.9,PIX,9491,Sim,36,9
2,9,Paulicéia,São Bernardo do Campo,2022-01-03,12:08,Beleza e cuidados pessoais,68.9,2,137.8,Cartão,5288,Não,39,9
3,4,Oswaldo Cruz,São Caetano do Sul,2022-01-03,9:29,Ferramentas e construção,80.9,5,404.5,PIX,9679,Sim,35,10
4,8,Parque das nações,Santo André,2022-01-03,13:02,Beleza e cuidados pessoais,165.0,4,660.0,PIX,1380,Não,50,9

In [18]:
pd.pivot_table(df,values="idade",index="metodo_pagamento",aggfunc="mean").round()

                  idade
metodo_pagamento
Carteira digital   28.0
Cartão             38.0
Dinheiro           46.0
PIX                40.0

In [23]:
pd.pivot_table(df,values="valor_total",index="categoria_produto",aggfunc="sum").sort_values("valor_total",ascending=False)

                            valor_total
categoria_produto
Eletrônicos                  14898778.5
Beleza e cuidados pessoais     423262.9
Casa e limpeza                 316688.6
Ferramentas e construção       252953.1
Alimentos e bebidas            231284.3
Livros                          75265.0
Papelaria e escritório          45221.6

In [24]:
df.head(2)

,ID_compra,unidade,cidade,data,horario,categoria_produto,valor_unitario,quantidade,valor_total,metodo_pagamento,ID_cliente,programa_cashback,idade,avaliacao_compra
0,6,Parque das nações,Santo André,2022-01-03,15:40,Eletrônicos,4457.9,4,17831.6,Dinheiro,6149,Sim,30,10
1,5,Oswaldo Cruz,São Caetano do Sul,2022-01-03,16:48,Ferramentas e construção,115.9,1,115.9,PIX,9491,Sim,36,9

In [26]:
pd.pivot_table(df,values="valor_total",index=["unidade","categoria_produto"],aggfunc="sum")

                                              valor_total
unidade           categoria_produto
Oswaldo Cruz      Alimentos e bebidas             73651.0
                  Beleza e cuidados pessoais     147369.2
                  Casa e limpeza                 109012.4
                  Eletrônicos                   5347950.7
                  Ferramentas e construção        92520.6
                  Livros                          27544.6
                  Papelaria e escritório          13164.5
Parque das nações Alimentos e bebidas             93104.5
                  Beleza e cuidados pessoais     106744.0
                  Casa e limpeza                  96788.6
                  Eletrônicos                   5022337.7
                  Ferramentas e construção        86618.1
                  Livros                          22458.5
                  Papelaria e escritório          15726.7
Paulicéia         Alimentos e bebidas             64528.8
                  Beleza e cuidados pessoais     169149.7
                  Casa e limpeza                 110887.6
                  Eletrônicos                   4528490.1
                  Ferramentas e construção        73814.4
                  Livros                          25261.9
                  Papelaria e escritório          16330.4

In [27]:
  pd.pivot_table(df,values="valor_total",index=["unidade"],columns=["categoria_produto"],aggfunc="sum")

categoria_produto,Alimentos e bebidas,Beleza e cuidados pessoais,Casa e limpeza,Eletrônicos,Ferramentas e construção,Livros,Papelaria e escritório
unidade,,,,,,,
Oswaldo Cruz,73651.0,147369.2,109012.4,5347950.7,92520.6,27544.6,13164.5
Parque das nações,93104.5,106744.0,96788.6,5022337.7,86618.1,22458.5,15726.7
Paulicéia,64528.8,169149.7,110887.6,4528490.1,73814.4,25261.9,16330.4

In [32]:
unidade_categoria_final=df.pivot_table(
    index="unidade",
    values="valor_total",
    columns="categoria_produto",
    aggfunc="sum",
    fill_value=0,
    margins=True,
    margins_name="Total"
    )
unidade_categoria_final

categoria_produto,Alimentos e bebidas,Beleza e cuidados pessoais,Casa e limpeza,Eletrônicos,Ferramentas e construção,Livros,Papelaria e escritório,Total
unidade,,,,,,,,
Oswaldo Cruz,73651.0,147369.2,109012.4,5347950.7,92520.6,27544.6,13164.5,5811213.0
Parque das nações,93104.5,106744.0,96788.6,5022337.7,86618.1,22458.5,15726.7,5443778.1
Paulicéia,64528.8,169149.7,110887.6,4528490.1,73814.4,25261.9,16330.4,4988462.9
Total,231284.3,423262.9,316688.6,14898778.5,252953.1,75265.0,45221.6,16243454.0

In [35]:
df=pd.read_csv("https://raw.githubusercontent.com/alura-cursos/python_dados/refs/heads/main/Dados/dados_automoveis.csv")
display(df)

,Marca,Modelo,Ano,Tipo_combustivel,Potencia_motor,Cilindros_motor,Tipo_transmissao,Rodas_motrizes,Numero_portas,Tamanho,Estilo,Consumo_estrada_milhas,Consumo_cidade_milhas,Valor($)
0,GMC,Envoy XL,2005,gasolina comum,275.0,6.0,automatico,tracao traseira,4.0,grande,SUV 4 portas,18,13,29695
1,Volkswagen,Passat,2016,gasolina comum,170.0,4.0,automatico,tracao dianteira,4.0,medio,seda,38,25,30495
2,Honda,Odyssey,2016,gasolina comum,248.0,6.0,automatico,tracao dianteira,4.0,grande,minivan de passageiros,28,19,37650
3,Chevrolet,Cruze,2015,gasolina comum,138.0,4.0,manual,tracao dianteira,4.0,medio,seda,36,25,16170
4,Volvo,740,1991,gasolina comum,162.0,4.0,automatico,tracao traseira,4.0,medio,seda,20,17,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10913,Toyota,Venza,2014,gasolina comum,181.0,4.0,automatico,tracao dianteira,4.0,medio,perua,26,20,27950
10914,Pontiac,G6,2009,flex (gasolina/E85),219.0,6.0,automatico,tracao dianteira,4.0,medio,seda,26,17,24710
10915,Volkswagen,Golf GTI,2016,gasolina premium (recomendada),220.0,4.0,manual automatizado,tracao dianteira,2.0,compacto,hatchback 2 portas,33,25,27590
10916,Saab,9-5,2009,gasolina premium (recomendada),260.0,4.0,automatico,tracao dianteira,4.0,medio,perua,27,17,43270
10917,Lexus,NX 200t,2015,gasolina premium (obrigatoria),235.0,4.0,automatico,tracao integral,4.0,medio,SUV 4 portas,28,21,35880

In [36]:
pd.pivot_table(df,values="Valor($)",index="Estilo").sort_values("Valor($)",ascending=False)

                             Valor($)
Estilo
picape cabine dupla      37220.466960
SUV 4 portas             36274.644799
conversivel              35247.457658
van de passageiros       29015.203125
seda                     28844.134643
cupe                     28167.933638
minivan de passageiros   25621.050360
perua                    25292.881356
picape cabine estendida  22488.776886
hatchback 4 portas       22420.866097
minivan de carga         20920.985915
SUV Conversível          17424.137931
hatchback 2 portas       16867.713439
picape cabine simples    15953.709184
van de carga             15280.221053
SUV 2 portas             10115.188406

In [38]:
df.head(2)

,Marca,Modelo,Ano,Tipo_combustivel,Potencia_motor,Cilindros_motor,Tipo_transmissao,Rodas_motrizes,Numero_portas,Tamanho,Estilo,Consumo_estrada_milhas,Consumo_cidade_milhas,Valor($)
0,GMC,Envoy XL,2005,gasolina comum,275.0,6.0,automatico,tracao traseira,4.0,grande,SUV 4 portas,18,13,29695
1,Volkswagen,Passat,2016,gasolina comum,170.0,4.0,automatico,tracao dianteira,4.0,medio,seda,38,25,30495

In [41]:
pd.pivot_table(df,values="Valor($)",index="Tipo_transmissao").sort_values("Valor($)",ascending=False).round()

                     Valor($)
Tipo_transmissao
transmissao direta    36947.0
manual automatizado   34839.0
automatico            32172.0
manual                17885.0
desconhecido           3041.0

In [45]:
pd.pivot_table(df,values="Valor($)",index="Ano",aggfunc=["min","mean","max"]).round()

          min     mean      max
     Valor($) Valor($) Valor($)
Ano
1990     2000   2020.0     3083
1991     2000   2081.0     5667
1992     2000   2078.0     5895
1993     2000   2187.0     7523
1994     2000   2312.0    27736
1995     2000   2607.0    30709
1996     2000   2497.0    18255
1997     2000   3105.0    39669
1998     2000   2976.0    25279
1999     2000   3096.0    20105
2000     2000   3167.0    20901
2001     9299  23237.0    45990
2002    12815  24297.0    51785
2003    10245  24940.0    51650
2004    10135  26429.0    64600
2005    10325  26786.0    66950
2006    12780  27790.0    67395
2007    12895  27408.0    67395
2008    12895  28335.0    68340
2009    11965  30428.0    66805
2010    11965  30986.0    68785
2011    11965  34000.0    70750
2012    13699  32212.0    73850
2013    14720  33366.0    69640
2014    12995  34241.0    69980
2015    11990  35125.0    74000
2016    11990  36137.0    73900
2017    11990  36773.0    73905

In [47]:
df.head(2)

,Marca,Modelo,Ano,Tipo_combustivel,Potencia_motor,Cilindros_motor,Tipo_transmissao,Rodas_motrizes,Numero_portas,Tamanho,Estilo,Consumo_estrada_milhas,Consumo_cidade_milhas,Valor($)
0,GMC,Envoy XL,2005,gasolina comum,275.0,6.0,automatico,tracao traseira,4.0,grande,SUV 4 portas,18,13,29695
1,Volkswagen,Passat,2016,gasolina comum,170.0,4.0,automatico,tracao dianteira,4.0,medio,seda,38,25,30495

In [49]:
pd.pivot_table(df,values="Valor($)",index=["Estilo","Potencia_motor","Cilindros_motor","Consumo_estrada_milhas","Consumo_cidade_milhas"]).round()

                                                                                                Valor($)
Estilo             Potencia_motor Cilindros_motor Consumo_estrada_milhas Consumo_cidade_milhas
SUV 2 portas       95.0           4.0             26                     22                       2000.0
                   140.0          6.0             20                     15                       2000.0
                                                                         16                       2000.0
                   150.0          6.0             18                     14                       2000.0
                                                  22                     15                       2000.0
...                                                                                                  ...
van de passageiros 280.0          8.0             17                     11                      34018.0
                   285.0          8.0             16                     11                      35743.0
                                                  17                     11                      34758.0
                   310.0          6.0             19                     14                      43196.0
                                  8.0             17                     13                      32748.0

[3016 rows x 1 columns]